#!/bin/bash
set -e

echo "🦚 INICIANDO PROTOCOLO: TRYONYOU–ABVETOS–ULTRA–PLUS–ULTIMATUM"

# 1. Verificación de Seguridad
if [ ! -f "package.json" ]; then
    echo "❌ Error: Ejecuta esto en la raíz del proyecto (donde está package.json)"
    exit 1
fi

# 2. Sincronización
echo "🔄 Sincronizando con rama main..."
git checkout main || git checkout -b main
git pull origin main || echo "⚠️ No se pudo hacer pull, continuando con local..."

# 3. Limpieza Profunda (Destructiva)
echo "🧹 Ejecutando limpieza de arquitectura..."
rm -rf node_modules dist legacy_old temp_old apps/web-old tests-old legacy integrations/duplicados
echo "✅ Limpieza completada."

# 4. Instalación Fresca
echo "📦 Instalando dependencias (Vite 7.1.2 + React 18.3.1)..."
npm install

# 5. Estructura de Directorios Divineo
echo "📂 Verificando estructura de directorios..."
mkdir -p src/modules/{avatar3D,pau,cap,abvet,wardrobe,ftt}
mkdir -p public/assets/{catalog,branding,ui}
mkdir -p public/docs/{patent,investor}

# 6. Preparar Staging
echo "➕ Añadiendo archivos al stage..."
git add .

# 7. COMMIT MAESTRO (Definición del Ecosistema)
echo "💎 Generando SuperCommit..."
git commit -m "🔥 TRYONYOU–ABVETOS–ULTRA–PLUS–ULTIMATUM

✅ Consolidated Architecture: Avatar3D, PAU, CAP, ABVET, Wardrobe, FTT.
✅ Integrated Deploy Express + CI/CD.
✅ Cleaned legacy repositories & dependencies.
✅ Legal: Project aligned with Patent PCT/EP2025/067317.

MODULES INTEGRATED:
- PAU (Personal Avatar Unit): Emotional AI Recommendations.
- ABVET: Biometric Payment (Iris/Voice).
- CAP: Just-in-Time Auto-Production.
- Wardrobe: Smart & Solidarity ecosystem.

INFRASTRUCTURE:
- Frontend: Vite 7.1.2 + React 18.3.1
- Deploy: Vercel Production
- SSL: Strict Mode

Commit generated by Agente 70 — SuperCommit MAX" || echo "⚠️ Nada nuevo que commitear."

# 8. Push a GitHub
echo "🚀 Enviando a GitHub..."
git push origin main

# 9. Despliegue Automático (Si existe token)
if [ -n "$VERCEL_TOKEN" ]; then
    echo "🌐 Desplegando a Vercel Producción..."
    npx vercel --prod --token=$VERCEL_TOKEN --yes --force
else
    echo "ℹ️ VERCEL_TOKEN no detectado. El código está en GitHub, pero el deploy manual es necesario."
fi

echo "✅ OPERACIÓN COMPLETADA: El sistema está sincronizado."
