/**
 * TryOnYou Assets - Auto-generated Path Constants
 * 
 * This file is auto-generated by scripts/import-assets.js
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 * 
 * To regenerate: npm run import:assets
 * 
 * @version 1.0.0
 * @generated 2025-12-09T18:24:09.295Z
 */

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

export type TryonImage = string;

// ============================================================================
// ASSET PATHS
// ============================================================================

const BASE_PATH = '/assets/images/tryonyou';

/**
 * Complete asset map for TryOnYou - Auto-generated
 */
export const TRYON_ASSETS = {
};

/**
 * Get all asset paths as a flat array
 */
export function getAllAssetPaths(): TryonImage[] {
  return [];
}

/**
 * Total number of assets
 */
export const TOTAL_ASSETS = 0;

/**
 * Assets by category count
 */
export const ASSETS_BY_CATEGORY = {};

export default TRYON_ASSETS;
