#!/usr/bin/env node

/**
 * TryOnYou Asset Import Script
 * 
 * This script scans the asset directory and generates:
 * - Updated TypeScript constants file with all asset paths
 * - JSON manifest with asset metadata
 * 
 * @version 1.0.0
 * @agent Agente 70 - Visual Integration & Orchestration
 */

import { existsSync, readdirSync, statSync, writeFileSync } from 'fs';
import { join, extname, basename, relative } from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

// ============================================================================
// CONFIGURATION
// ============================================================================

const BASE_PATH = join(__dirname, '..', 'assets', 'images', 'tryonyou');
const OUTPUT_JSON = join(__dirname, '..', 'docs', 'assets', 'tryonyou-assets.json');
const OUTPUT_TS = join(__dirname, '..', 'src', 'constants', 'TryonAssets.generated.ts');

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Recursively get all files in directory with metadata
 */
function scanDirectory(dir, basePath = dir) {
  if (!existsSync(dir)) {
    return [];
  }
  
  const files = readdirSync(dir);
  const result = [];
  
  files.forEach(file => {
    const filepath = join(dir, file);
    const stat = statSync(filepath);
    
    if (stat.isDirectory()) {
      result.push(...scanDirectory(filepath, basePath));
    } else if (stat.isFile() && file !== '.gitkeep') {
      const ext = extname(file).toLowerCase();
      const relativePath = relative(basePath, filepath);
      const webPath = `/assets/images/tryonyou/${relativePath.replace(/\\/g, '/')}`;
      
      result.push({
        filename: file,
        path: filepath,
        webPath,
        category: relativePath.split('/')[0] || 'root',
        subcategory: relativePath.split('/')[1] || null,
        size: stat.size,
        extension: ext.replace('.', ''),
        modified: stat.mtime,
      });
    }
  });
  
  return result;
}

/**
 * Group files by category structure
 */
function groupByCategory(files) {
  const grouped = {};
  
  files.forEach(file => {
    const parts = file.webPath.split('/');
    const pathParts = parts.slice(4); // Remove /assets/images/tryonyou/
    
    let current = grouped;
    
    for (let i = 0; i < pathParts.length - 1; i++) {
      const part = pathParts[i];
      if (!current[part]) {
        current[part] = {};
      }
      current = current[part];
    }
    
    const filename = pathParts[pathParts.length - 1];
    if (!current._files) {
      current._files = [];
    }
    current._files.push(file.webPath);
  });
  
  return grouped;
}

/**
 * Generate TypeScript constant from grouped data
 */
function generateTypeScript(grouped, files) {
  const header = `/**
 * TryOnYou Assets - Auto-generated Path Constants
 * 
 * This file is auto-generated by scripts/import-assets.js
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 * 
 * To regenerate: npm run import:assets
 * 
 * @version 1.0.0
 * @generated ${new Date().toISOString()}
 */

// ============================================================================
// TYPE DEFINITIONS
// ============================================================================

export type TryonImage = string;

// ============================================================================
// ASSET PATHS
// ============================================================================

const BASE_PATH = '/assets/images/tryonyou';

`;

  let content = header;
  
  // Generate the main export object
  content += '/**\n * Complete asset map for TryOnYou - Auto-generated\n */\n';
  content += 'export const TRYON_ASSETS = {\n';
  
  // Add each category
  Object.keys(grouped).forEach(category => {
    content += `  // ${category.charAt(0).toUpperCase() + category.slice(1)} assets\n`;
    content += `  ${category}: `;
    content += generateCategoryObject(grouped[category], 2);
    content += ',\n\n';
  });
  
  content += '};\n\n';
  
  // Add helper functions
  content += `/**
 * Get all asset paths as a flat array
 */
export function getAllAssetPaths(): TryonImage[] {
  return ${JSON.stringify(files.map(f => f.webPath), null, 2)};
}

/**
 * Total number of assets
 */
export const TOTAL_ASSETS = ${files.length};

/**
 * Assets by category count
 */
export const ASSETS_BY_CATEGORY = ${JSON.stringify(
  Object.keys(grouped).reduce((acc, cat) => {
    acc[cat] = countFilesInCategory(grouped[cat]);
    return acc;
  }, {}),
  null,
  2
)};

export default TRYON_ASSETS;
`;
  
  return content;
}

/**
 * Count files in a category recursively
 */
function countFilesInCategory(obj) {
  let count = 0;
  
  if (obj._files) {
    count += obj._files.length;
  }
  
  Object.keys(obj).forEach(key => {
    if (key !== '_files' && typeof obj[key] === 'object') {
      count += countFilesInCategory(obj[key]);
    }
  });
  
  return count;
}

/**
 * Generate object structure for a category
 */
function generateCategoryObject(obj, indent = 0) {
  const spaces = '  '.repeat(indent);
  
  if (obj._files && Object.keys(obj).length === 1) {
    // Only files, return array
    return JSON.stringify(obj._files, null, 2).replace(/\n/g, '\n' + spaces);
  }
  
  let result = '{\n';
  
  Object.keys(obj).forEach(key => {
    if (key === '_files') {
      if (obj._files.length > 0) {
        result += `${spaces}  files: ${JSON.stringify(obj._files, null, 2).replace(/\n/g, '\n' + spaces + '  ')},\n`;
      }
    } else {
      result += `${spaces}  ${key}: `;
      result += generateCategoryObject(obj[key], indent + 1);
      result += ',\n';
    }
  });
  
  result += `${spaces}}`;
  return result;
}

/**
 * Generate JSON manifest
 */
function generateJSON(files) {
  const manifest = {
    version: '1.0.0',
    generated: new Date().toISOString(),
    totalAssets: files.length,
    categories: {},
    assets: files.map(f => ({
      filename: f.filename,
      path: f.webPath,
      category: f.category,
      subcategory: f.subcategory,
      size: f.size,
      sizeKB: Math.round(f.size / 1024),
      sizeMB: (f.size / (1024 * 1024)).toFixed(2),
      extension: f.extension,
      modified: f.modified,
    })),
  };
  
  // Count by category
  files.forEach(f => {
    if (!manifest.categories[f.category]) {
      manifest.categories[f.category] = 0;
    }
    manifest.categories[f.category]++;
  });
  
  return JSON.stringify(manifest, null, 2);
}

// ============================================================================
// MAIN
// ============================================================================

function main() {
  console.log('📦 TryOnYou Asset Import Tool\n');
  console.log(`📁 Scanning: ${BASE_PATH}\n`);
  
  if (!existsSync(BASE_PATH)) {
    console.log('❌ Error: Assets directory not found!');
    console.log(`   Expected: ${BASE_PATH}`);
    console.log('\n💡 Creating directory structure...');
    process.exit(1);
  }
  
  // Scan directory
  const files = scanDirectory(BASE_PATH);
  
  if (files.length === 0) {
    console.log('⚠️  Warning: No asset files found!');
    console.log('\n💡 The directory structure exists but contains no images.');
    console.log('   Generating empty manifest...\n');
  } else {
    console.log(`✅ Found ${files.length} asset(s)\n`);
  }
  
  // Group by category
  const grouped = groupByCategory(files);
  
  // Generate TypeScript
  console.log('📝 Generating TypeScript constants...');
  const tsContent = generateTypeScript(grouped, files);
  writeFileSync(OUTPUT_TS, tsContent, 'utf8');
  console.log(`   ✅ Created: ${relative(process.cwd(), OUTPUT_TS)}`);
  
  // Generate JSON manifest
  console.log('\n📝 Generating JSON manifest...');
  const jsonContent = generateJSON(files);
  writeFileSync(OUTPUT_JSON, jsonContent, 'utf8');
  console.log(`   ✅ Created: ${relative(process.cwd(), OUTPUT_JSON)}`);
  
  // Print summary
  console.log('\n' + '='.repeat(60));
  console.log('📊 Summary:');
  console.log(`   • Total assets: ${files.length}`);
  console.log(`   • Categories: ${Object.keys(grouped).length}`);
  console.log(`   • Output files: 2`);
  console.log('='.repeat(60));
  
  console.log('\n✨ Import complete!\n');
  console.log('Next steps:');
  console.log('  1. Review generated files');
  console.log('  2. Import in your code:');
  console.log('     import { TRYON_ASSETS } from "@/constants/TryonAssets.generated";');
  console.log('  3. Run validation:');
  console.log('     npm run check:assets\n');
}

main();
