name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install

      - name: Install web app dependencies
        run: cd apps/web && npm install

      - name: Build web app
        run: cd apps/web && npm run build

      - name: Deploy to Vercel
        run: |
          npm install -g vercel@latest
          vercel pull --yes --environment=production --token "${{ secrets.VERCEL_TOKEN }}"
          vercel deploy --prod --token "${{ secrets.VERCEL_TOKEN }}"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}