name: EnsureCloseISO49OnPR53Merge
on:
  pull_request:
    types: [closed]
permissions:
  issues: write
jobs:
  ensure-close:
    if: github.event.pull_request.merged == true && github.event.pull_request.number == 53
    runs-on: ubuntu-latest
    steps:
      - name: Close issue #49 (idempotent)
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = 49;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body: "Closed automatically because PR #53 was merged."
            });
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              state: "closed"
            });
