name: Health Check

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Empaquetar logs
        if: ${{ always() }}
        run: |
          mkdir -p logs && cp -R $GITHUB_WORKSPACE logs/workspace || true

      - name: Subir artefacto de logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ github.run_id }}
          path: logs
          retention-days: 7